blank_issues_enabled: true
contact_links:
  - name: Get support on Discord
    url: https://discord.com/channels/709930458086899723/960717444656287774
    about: Get help from the maintainers on Discord
  - name: Ask a question, give feedback, share your project
    url: https://github.com/CodingCatDev/discussions
    about: Connect with other community members with GitHub discussions
